import Head from 'next/head'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AuthShowcase></AuthShowcase> */}
      <main>
        <h1>Welcome to Appsus!</h1>
      </main>
    </>
  )
}

export default Home

