import styles from './index.module.css'
import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { signIn, signOut, useSession } from 'next-auth/react'

import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  const { data: session, status } = useSession()
  const { data, isLoading, isError, error } = trpc.mail.getAll.useQuery(undefined, {
    enabled: session?.user !== undefined,
  })

  // if (isLoading) return <div>Loading...</div>
  if (isError) return <div>{error.message}</div>
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthShowcase></AuthShowcase>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Appsus!</h1>
      </main>
    </>
  )
}

export default Home

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession()

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  )

  return (
    <div className={styles.authContainer}>
      <p className={styles.showcaseText}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button onClick={sessionData ? () => signOut() : () => signIn()}>{sessionData ? 'Sign out' : 'Sign in'}</button>
    </div>
  )
}

